version: "2.1"

services:
        microservice:
                image: cloudgeekview/microservice:v2
                container_name: my-microservice
                ports:
                   - 9999:9999
                restart: always
                mem_limit: 512m

        database:
                image: mysql:5
                container_name: my-databases
                volumes:
                   - mysql-data:/var/lib/mysql
                ports:
                   - 3306:3306
                environment:
                   - MYSQL_ROOT_PASSWORD=Yagna123
                restart: always

volumes:
       mysql-data:
          driver: local


