version: "3"

services:
        microservice:
                image: cloudgeekview/microservice
                container_name: my-microservice
                ports:
                   - 9999:9999


        database:
                image: mysql:5
                container_name: my-databases
                ports:
                   - 3306:3306
                environment:
                   - MYSQL_ROOT_PASSWORD=Yagna123

